version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build: .
    image: sadko-dostavka
    restart: always
    env_file:
      - .env
    volumes:
      - media_data:/app/sadko/media
      - static_data:/app/sadko/static
    networks:
      - backend
    depends_on:
      - db
    entrypoint: sh /app/entrypoint.sh
  server:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - media_data:/app/sadko/media
      - static_data:/app/sadko/static
    networks:
      - backend
    depends_on:
      - app
networks:
  backend:
volumes:
  db_data:
  media_data:
  static_data:
