version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build: .
    image: sadko-dostavka
    restart: always
    env_file:
      - .env
    volumes:
      - media_data:/app/sadko/media
    networks:
      - backend
    ports:
      - 80:8000
    depends_on:
      - db
    entrypoint: sh /app/entrypoint.sh
networks:
  backend:
volumes:
  db_data:
  media_data:
