# Generated by Django 4.2.1 on 2023-05-08 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import menu.models
import menu.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание блюда')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=9999, message='Максимальная цена 9999')], verbose_name='Цена')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать')),
                ('category', models.ForeignKey(default=menu.models.Category.get_or_create_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dishes', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=menu.utils.get_image_path_name, verbose_name='Фото блюда')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Фотографии блюда',
                'verbose_name_plural': 'Фотографии блюд',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['position'], name='menu_catego_positio_81cd34_idx'),
        ),
        migrations.AddIndex(
            model_name='dishimage',
            index=models.Index(fields=['position'], name='menu_dishim_positio_d9de4b_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['position', 'title'], name='menu_dish_positio_53a5ff_idx'),
        ),
    ]
